### ISSUE TITLE
Tensorflow-lite build workaround

### ISSUE THREAD

**Issue by bastien-sagetat** [Photohead/photohead-linux-app#22]
Current issue just act as a reminder, because the issue needs to be fixed in the tensorflow github:
tensorflow issue: https://github.com/tensorflow/tensorflow/issues/62381

Tensorflow-lite build fails when using the following command:
`cmake ../tensorflow/lite/ -DTFLITE_ENABLE_INSTALL=ON -DFETCHCONTENT_FULLY_DISCONNECTED=OFF -DBUILD_SHARED_LIBS=ON`

Got the following error:
```
CMake Error in tools/cmake/modules/ml_dtypes/CMakeLists.txt:
  Target "ml_dtypes" INTERFACE_INCLUDE_DIRECTORIES property contains path:

    "/home/xxx/tensorflow/build/ml_dtypes/ml_dtypes"

  which is prefixed in the build directory.
```

**Did the following workaround to fix the issue.**
In /home/xxx/dev/tensorflow/tensorflow/lite/tools/cmake/modules/ml_dtypes/CMakeLists.txt
Replace:
```
target_include_directories(ml_dtypes INTERFACE
  "${ML_DTYPES_SOURCE_DIR}"
  "${ML_DTYPES_SOURCE_DIR}/ml_dtypes")
```
by
```
target_include_directories(ml_dtypes INTERFACE
  "$<BUILD_INTERFACE:${ML_DTYPES_SOURCE_DIR}>" "$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>"
  "$<BUILD_INTERFACE:${ML_DTYPES_SOURCE_DIR}/ml_dtypes>" "$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}/ml_dtypes>")
```

sources:
https://stackoverflow.com/questions/25676277/cmake-target-include-directories-prints-an-error-when-i-try-to-add-the-source
https://cmake.org/cmake/help/latest/command/target_include_directories.html
https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#export-and-install-expressions

**Comment by optimisan** [comment]
Thanks for this, I eventually found a script that installs tensorflow-lite here https://github.com/google/ml-compiler-opt/blob/main/buildbot/build_tflite.sh
Taking from `buildbot_init.sh` from the same repo:
```bash
    rm -rf /tmp/tflitebuild
    mkdir -p /tmp/tflitebuild
    pushd /tmp/tflitebuild
    curl https://raw.githubusercontent.com/google/ml-compiler-opt/main/buildbot/build_tflite.sh | bash -s
    popd
    # You'll get the tflite.cmake file which sets the paths to the libraries required
```

**Comment by bastien-sagetat** [comment]
Thanks @optimisan for the comment.
I actually did some [documentation](https://github.com/bastien-sagetat/photohead/blob/main/doc/soft_requirements.md) on how to setup tensorflow-lite:


To be honest, this project is at a standstill at the moment, although I'll certainly continue to work on it when I've got a bit more time.

Also, I will certainly get rid of tensorflow-lite, because of how painful it is  to build and install, compare to other solutions.
Some alternatives would be the following:
 - [ncnn](https://github.com/Tencent/ncnn) -> much less dependencies.
 - [Raspberry Pi AI HAT+](https://www.raspberrypi.com/products/ai-hat/)](https://www.raspberrypi.com/products/ai-hat/) -> more expensive solution but much better performances.

I'm definitely going to try out the Raspberry Pi AI HAT+.

If you have other suggestions, don't hesitate to keep me in touch.

**Comment by optimisan** [comment]
I did follow your [documentation](https://github.com/bastien-sagetat/photohead/blob/main/doc/soft_requirements.md) but somehow couldn't get tflite to install and managed to found that script in `ml-compiler-opt`.

(sorry I don't know anything about the Pi AI or ncnn, in fact, I have no idea about this project but it seems pretty cool - I have been getting into programming an ESP32 so might try something like this someday!)
